// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxQiHCfGC22cjm64IOJBytkH_CFOmYdkk',
    appId: '1:1083011169086:web:b19e9776e8259322354a6f',
    messagingSenderId: '1083011169086',
    projectId: 'push-notification-3a9b3',
    authDomain: 'push-notification-3a9b3.firebaseapp.com',
    storageBucket: 'push-notification-3a9b3.firebasestorage.app',
    measurementId: 'G-WPQ450J2PG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0W8C4ug1hKSRoWc2MGFL04jlJERi-umE',
    appId: '1:1083011169086:android:0cb90300c7fb169e354a6f',
    messagingSenderId: '1083011169086',
    projectId: 'push-notification-3a9b3',
    storageBucket: 'push-notification-3a9b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhFxH4kDqNYsYR6ZFxC1tjn-n8DDP6JX8',
    appId: '1:1083011169086:ios:8ff360153ab3f7b1354a6f',
    messagingSenderId: '1083011169086',
    projectId: 'push-notification-3a9b3',
    storageBucket: 'push-notification-3a9b3.firebasestorage.app',
    iosBundleId: 'com.fitvantage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhFxH4kDqNYsYR6ZFxC1tjn-n8DDP6JX8',
    appId: '1:1083011169086:ios:03d4f41959c876de354a6f',
    messagingSenderId: '1083011169086',
    projectId: 'push-notification-3a9b3',
    storageBucket: 'push-notification-3a9b3.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );
}
